import { buildAiaPlatinumWealthProduct, type ParseContext } from './aiaPlatinumWealthShared.js'

export function parseAiaPlatinumWealthLegacy(context: ParseContext) {
  return buildAiaPlatinumWealthProduct(context, {
    id: 'aia-platinum-wealth-legacy',
    productName: 'AIA Platinum Wealth Legacy',
    supportStatus: 'supported',
    economicsStatus: 'supported',
    catalogWarningLabel: 'supported V1 product for the regular-pay 5-year corridor',
    planKeyword: 'AIA Platinum Wealth Legacy',
    overviewPage: 1,
    premiumPage: 3,
    chargePage: 3,
    holidayPage: 4,
    topUpPage: 6,
    nonPaymentPage: 7,
    regularPremiumChargeSchedule: [
      { startPolicyYear: 1, endPolicyYear: 1, rate: 0.36 },
      { startPolicyYear: 2, endPolicyYear: 2, rate: 0.18 },
      { startPolicyYear: 3, endPolicyYear: 3, rate: 0.06 },
      { startPolicyYear: 4, endPolicyYear: 4, rate: 0.06 },
      { startPolicyYear: 5, endPolicyYear: 5, rate: 0.04 },
    ],
    premiumHolidayChargeSchedule: [
      { startPolicyYear: 1, endPolicyYear: 4, rate: 0.35 },
      { startPolicyYear: 5, endPolicyYear: 5, rate: 0 },
    ],
    regularFullSurrenderChargeSchedule: [0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.05],
    regularPartialWithdrawalChargeSchedule: [0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.05],
    modeledEconomics: [
      'branch:aia-platinum-wealth-legacy-regular-premium-charge',
      'branch:aia-platinum-wealth-legacy-top-up-premium-charge',
      'branch:aia-platinum-wealth-legacy-premium-holiday-charge',
      'branch:aia-platinum-wealth-legacy-partial-withdrawal-charge',
      'branch:aia-platinum-wealth-legacy-full-surrender-charge',
      'branch:aia-platinum-wealth-legacy-administration-charge-manual-input',
      'branch:aia-platinum-wealth-legacy-insurance-risk-charge-manual-input',
      'kernel:top-up-paid-up-to-date-block',
      'kernel:current-death-benefit-estimate',
      'kernel:current-ti-benefit-estimate',
      'kernel:current-residual-death-benefit-after-ti-estimate',
    ],
    coveredElsewhereBehaviors: ['aia-platinum-wealth-legacy-fund-management-charge'],
    metadataOnlyBehaviors: [
      'aia-platinum-wealth-legacy-single-premium-corridor',
      'aia-platinum-wealth-legacy-no-lapse-privilege',
      'aia-platinum-wealth-legacy-expiry-age-election',
      'aia-platinum-wealth-legacy-layering-and-adjusted-partial-withdrawal',
      'aia-platinum-wealth-legacy-no-fund-switching',
    ],
    productWarning: 'The parser captures premium-year regular premium charges, the 3% top-up premium charge with blocking in months where regular premiums are not paid when due, the premium-holiday charge schedule, the published regular-premium partial-withdrawal / surrender charge schedules, manual-input administration-charge and insurance-risk-charge placeholders sourced from the policy illustration, the current-state death benefit corridor via manual current insured amount, current amount owing, and current No Lapse Privilege mode inputs, and the current terminal-illness snapshot plus the current residual death-benefit estimate after a TI claim today from the same supported acceleration corridor after a manual remaining aggregate TI cap is supplied, while the single-pay corridor, no-lapse activation or expiry election mechanics, and terminal-illness claim exclusions / settlement workflow remain informational only beyond the modeled current ordinary death, terminal-illness, and residual-after-TI snapshot surface.',
    unsupportedItems: [
      'Single-pay corridor and the 5% single-premium charge remain informational only in V1.',
      'Administration charge is modeled only as a manual-input annualized placeholder because the applicable age / insured-amount rates live in the policy illustration rather than the product summary.',
      'The current death benefit needs manual current insured amount, current amount owing, and current No Lapse Privilege mode inputs because adjusted partial withdrawals and no-lapse history are not reconstructed from history in V1.',
      'Insurance Risk Charge is modeled only as a manual-input annualized placeholder because the applicable standard / non-standard life rates live in the policy illustration rather than the product summary. No Lapse Privilege activation or termination and expiry-age election mechanics remain informational only.',
      'Adjusted partial withdrawal, layer creation from insured-amount changes, and minimum-insured-amount gating remain informational only.',
      'The current terminal-illness snapshot and current residual death-benefit estimate after a TI claim today both need manual current insured amount, current amount owing, current No Lapse Privilege mode, and remaining aggregate TI cap inputs because adjusted partial withdrawals and TI usage are not reconstructed from history in V1.',
      'Terminal-illness claim exclusions, settlement workflow, and non-manual post-claim state remain informational only beyond the modeled current terminal-illness and residual-after-TI snapshot surface.',
      'Other protection-side payout handling remains informational only.',
      'Fund-level management charges and no-fund-switching constraints remain informational only.',
    ],
    buildAdditionalFeeRules: ({ chargeRef }) => [
      {
        id: 'administration-charge',
        label: 'Administration Charge',
        basis: 'fixed-annual',
        rate: 0,
        amount: 0,
        requiresManualInput: true,
        appliesTo: ['policy'],
        activeWindow: 'policy-term',
        startPolicyYear: 1,
        endPolicyYear: 10,
        notes: [
          'Manual-input approximation for the published monthly administration charge corridor during the first 10 policy years.',
          'Enter the annualized administration charge from the policy illustration. If the illustration shows a monthly amount, multiply it by 12.',
          'Rate depends on entry age and insured amount. The published summary does not include rate tables.',
        ],
        sourceRefs: [chargeRef],
      },
      {
        id: 'insurance-risk-charge',
        label: 'Insurance Risk Charge',
        basis: 'fixed-annual',
        rate: 0,
        amount: 0,
        requiresManualInput: true,
        appliesTo: ['policy'],
        activeWindow: 'policy-term',
        notes: [
          'Manual-input approximation for the monthly Insurance Risk Charge deducted on the prevailing sum-at-risk corridor.',
          'Enter the annualized Insurance Risk Charge from the policy illustration. If the illustration shows a monthly amount, multiply it by 12.',
          'Applicable rates depend on underwriting class and insurer illustration factors that are not published in the summary.',
        ],
        sourceRefs: [chargeRef],
      },
    ],
  })
}
