import { buildAiaPlatinumWealthProduct, type ParseContext } from './aiaPlatinumWealthShared.js'

export function parseAiaPlatinumWealthLegacy(context: ParseContext) {
  return buildAiaPlatinumWealthProduct(context, {
    id: 'aia-platinum-wealth-legacy',
    productName: 'AIA Platinum Wealth Legacy',
    supportStatus: 'supported',
    economicsStatus: 'supported',
    catalogWarningLabel: 'supported V1 product for the regular-pay 5-year corridor',
    planKeyword: 'AIA Platinum Wealth Legacy',
    overviewPage: 1,
    premiumPage: 3,
    chargePage: 3,
    holidayPage: 4,
    topUpPage: 6,
    nonPaymentPage: 7,
    regularPremiumChargeSchedule: [
      { startPolicyYear: 1, endPolicyYear: 1, rate: 0.36 },
      { startPolicyYear: 2, endPolicyYear: 2, rate: 0.18 },
      { startPolicyYear: 3, endPolicyYear: 3, rate: 0.06 },
      { startPolicyYear: 4, endPolicyYear: 4, rate: 0.06 },
      { startPolicyYear: 5, endPolicyYear: 5, rate: 0.04 },
    ],
    premiumHolidayChargeSchedule: [
      { startPolicyYear: 1, endPolicyYear: 4, rate: 0.35 },
      { startPolicyYear: 5, endPolicyYear: 5, rate: 0 },
    ],
    regularFullSurrenderChargeSchedule: [0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.05],
    regularPartialWithdrawalChargeSchedule: [0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.05],
    modeledEconomics: [
      'branch:aia-platinum-wealth-legacy-regular-premium-charge',
      'branch:aia-platinum-wealth-legacy-top-up-premium-charge',
      'branch:aia-platinum-wealth-legacy-premium-holiday-charge',
      'branch:aia-platinum-wealth-legacy-partial-withdrawal-charge',
      'branch:aia-platinum-wealth-legacy-full-surrender-charge',
      'kernel:top-up-paid-up-to-date-block',
      'kernel:current-death-benefit-estimate',
      'kernel:current-ti-benefit-estimate',
      'kernel:current-residual-death-benefit-after-ti-estimate',
    ],
    coveredElsewhereBehaviors: ['aia-platinum-wealth-legacy-fund-management-charge'],
    metadataOnlyBehaviors: [
      'aia-platinum-wealth-legacy-single-premium-corridor',
      'aia-platinum-wealth-legacy-administration-charge',
      'aia-platinum-wealth-legacy-insurance-risk-charge',
      'aia-platinum-wealth-legacy-no-lapse-privilege',
      'aia-platinum-wealth-legacy-expiry-age-election',
      'aia-platinum-wealth-legacy-layering-and-adjusted-partial-withdrawal',
      'aia-platinum-wealth-legacy-no-fund-switching',
    ],
    productWarning: 'The parser captures premium-year regular premium charges, the 3% top-up premium charge with blocking in months where regular premiums are not paid when due, the premium-holiday charge schedule, the published regular-premium partial-withdrawal / surrender charge schedules, the current-state death benefit corridor via manual current insured amount, current amount owing, and current No Lapse Privilege mode inputs that remain user-supplied by design in this app, and the current terminal-illness snapshot plus the current residual death-benefit estimate after a TI claim today from the same supported acceleration corridor after a manual remaining aggregate TI cap is supplied, while the single-pay corridor, administration charge, insurance risk charge, no-lapse activation or expiry election mechanics, and terminal-illness claim exclusions / settlement workflow remain informational only beyond the modeled current ordinary death, terminal-illness, and residual-after-TI snapshot surface.',
    unsupportedItems: [
      'Single-pay corridor and the 5% single-premium charge remain informational only in V1.',
      'Administration charge remains informational only because the applicable rates live in the policy illustration rather than the product summary.',
      'The current death benefit keeps manual current insured amount, current amount owing, and current No Lapse Privilege mode inputs because adjusted partial-withdrawal history, debt, and no-lapse state are live policy facts this app cannot observe; those inputs are manual by design in V1.',
      'Insurance Risk Charge, No Lapse Privilege activation or termination, and expiry-age election mechanics remain informational only.',
      'Adjusted partial withdrawal, layer creation from insured-amount changes, and minimum-insured-amount gating remain informational only.',
      'The current terminal-illness snapshot and current residual death-benefit estimate after a TI claim today both keep manual current insured amount, current amount owing, current No Lapse Privilege mode, and remaining aggregate TI cap inputs because debt, no-lapse status, and cross-policy TI usage are current policy facts this app cannot observe; those inputs are manual by design in V1.',
      'Terminal-illness claim exclusions, settlement workflow, and non-manual post-claim state remain informational only beyond the modeled current terminal-illness and residual-after-TI snapshot surface.',
      'Other protection-side payout handling remains informational only.',
      'Fund-level management charges and no-fund-switching constraints remain informational only.',
    ],
  })
}
